apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer-bridge-webhook-n17
  namespace: overseer
  labels:
    app: overseer-bridge-webhook-n17
spec:
  selector:
    matchLabels:
      app: overseer-bridge-webhook-n17
  replicas: 1
  template:
    metadata:
      labels:
        app: overseer-bridge-webhook-n17
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - overseer-bridge-webhook-n17
              topologyKey: kubernetes.io/hostname
      containers:
        - name: overseer-bridge-webhook-n17
          image: cmaster11/overseer-webhook-bridge:release-1.11-4
          args:
            - -redis-host
            - redis:6379
            # If using the webhook queue to clone test results
            #  - -redis-queue-key
            #  - "overseer.results.n17"
            # Url where to send tests' results
            - -url
            - "https://hook.notify17.net/api/template/2rJlapyPtetACu88LG18aXSB3NLKuXa02fG-InuV77A"
            - -send-test-recovered=true
